export interface GenerateMakefileOptions {
  verilogSources: string[];
  toplevel: string;
  pythonModule: string;
  simulator?: string;
}

export function generateCocotbMakefile(options: GenerateMakefileOptions): string {
  const sim = options.simulator || "icarus";
  const sources = options.verilogSources.join(" ");

  return `# Cocotb Simulation Makefile
# Generated by @zesun33/mcp-cocotb

SIM ?= ${sim}
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES ?= ${sources}
TOPLEVEL = ${options.toplevel}
MODULE = ${options.pythonModule}

# Cocotb standard makefile inclusion
include $(shell cocotb-config --makefiles)/Makefile.sim
`;
}
